# Generated by Django 4.2.2 on 2025-08-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_status_type_alter_cashflow_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
