# Generated by Django 4.2.2 on 2025-08-25 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_alter_cashflow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date_was_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
